version: "3"

services:
  app:
    build:
      context: app
    container_name: app
    restart: always


  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert.crt:/etc/ssl/certs/cert.crt:ro
      - ./nginx/cert.key:/etc/ssl/private/cert.key:ro
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - app